# Generated by Django 3.2.4 on 2021-06-18 23:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.CharField(max_length=200, unique=True)),
                ('jse_code', models.CharField(max_length=200, unique=True)),
                ('price', models.CharField(max_length=200)),
                ('move', models.CharField(max_length=200)),
                ('move_change', models.CharField(max_length=200)),
                ('market_cap', models.CharField(max_length=200)),
                ('time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'ordering': ['id'],
            },
        ),
    ]
